language: go

go:
  - 1.14.x

os: osx

before_install:
  - go get -u golang.org/x/lint/golint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - go vet
  - golint
  - golangci-lint run ./...

notifications:
  email: false
